context:
  name: subfinder
  version: "2.6.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/projectdiscovery/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 3ce0d4ddcca869d459a2571a2c1b437456007109e5d6ebfc4d3fdcea6a6edca7
  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    file_name: xz-LICENSE-1
  - url: https://raw.githubusercontent.com/tukaani-project/xz/refs/heads/master/COPYING
    sha256: aedbbc280610875b83e246f05957369f84acf9abdb86b884a9ff2f5dd65e8ffb
    file_name: xz-LICENSE-2

build:
  script:
    - cd v2
    - if: unix
      then:
        - go build -o $PREFIX/bin/subfinder ./cmd/subfinder
      else:
        - go build -o %PREFIX%\bin\subfinder.exe .\cmd\subfinder
    - go-licenses save ./cmd/subfinder --save_path=../library_licenses
        --ignore=github.com/projectdiscovery/subfinder 
        --ignore github.com/xi2/xz
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script:
      content: subfinder --version

about:
  homepage: https://github.com/projectdiscovery/subfinder
  summary: Fast passive subdomain enumeration tool
  description: |
    subfinder is a subdomain discovery tool that returns valid subdomains for websites, using passive online sources. It has a simple, modular architecture and is optimized for speed. subfinder is built for doing one thing only - passive subdomain enumeration, and it does that very well.
  license: MIT
  license_file:
    - LICENSE.md
    - library_licenses
    - xz-LICENSE-1
    - xz-LICENSE-2
  repository: https://github.com/projectdiscovery/subfinder

extra:
  recipe-maintainers:
    - pavelzw
